"""crear tablas ubicacion y sububicacion

Revision ID: 0dcc43df5c7e
Revises: ab4bcc0935ae
Create Date: 2026-08-20 21:33:31.912152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0dcc43df5c7e'
down_revision: Union[str, Sequence[str], None] = 'ab4bcc0935ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('encargado', sa.String(length=100), nullable=True),
    sa.Column('hora_apertura', sa.Time(), nullable=True),
    sa.Column('hora_cierre', sa.Time(), nullable=True),
    sa.Column('activo', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sububicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('encargado', sa.String(length=100), nullable=True),
    sa.Column('activo', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sububicacion')
    op.drop_table('ubicacion')
    # ### end Alembic commands ###
