"""agregar fecha_creacion a usuario

Revision ID: 0f11a4e53d50
Revises: abaca6f1b9b5
Create Date: 2026-09-06 23:03:07.246891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f11a4e53d50'
down_revision: Union[str, Sequence[str], None] = 'abaca6f1b9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_general', sa.Column('id_ubicacion', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configuracion_general', 'ubicacion', ['id_ubicacion'], ['id'])
    op.add_column('usuario', sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fecha_creacion')
    op.drop_constraint(None, 'configuracion_general', type_='foreignkey')
    op.drop_column('configuracion_general', 'id_ubicacion')
    # ### end Alembic commands ###
