"""crear tablas compra detalle_compra compra_pago nota_entrega devolucion_compra

Revision ID: 410c03b57e79
Revises: 59e77218bb61
Create Date: 2026-08-22 00:33:51.982996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '410c03b57e79'
down_revision: Union[str, Sequence[str], None] = '59e77218bb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion_destino', sa.Integer(), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('iva', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_registra', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento_pago', sa.Date(), nullable=True),
    sa.Column('saldo_pendiente', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion_destino'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_registra'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compra_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_tipo_pago', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_comprada', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('cantidad_unidades', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('costo_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucion_compra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_entrega',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('numero_nota', sa.String(length=50), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario_receptor', sa.Integer(), nullable=True),
    sa.Column('conforme', mysql.TINYINT(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_receptor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_entrega')
    op.drop_table('devolucion_compra')
    op.drop_table('detalle_compra')
    op.drop_table('compra_pago')
    op.drop_table('compra')
    # ### end Alembic commands ###
