"""agregar motivo_cancelacion a compra y anulado a compra_pago

Revision ID: 70bf0a7c9236
Revises: 77014e8739d3
Create Date: 2026-09-18 10:42:37.859832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bf0a7c9236'
down_revision: Union[str, Sequence[str], None] = '77014e8739d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compra', sa.Column('motivo_cancelacion', sa.Text(), nullable=True))
    op.add_column('compra_pago', sa.Column('anulado', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compra_pago', 'anulado')
    op.drop_column('compra', 'motivo_cancelacion')
    # ### end Alembic commands ###
