"""add activo to tipo_proveedor

Revision ID: 77014e8739d3
Revises: 7c9eeba5e3bd
Create Date: 2026-09-15 19:54:20.615563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77014e8739d3'
down_revision: Union[str, Sequence[str], None] = '7c9eeba5e3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_proveedor', sa.Column('activo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_proveedor', 'activo')
    # ### end Alembic commands ###
