"""add activo to tipo_pago and tipo_gasto

Revision ID: 7c9eeba5e3bd
Revises: 8056fb9dcdd4
Create Date: 2026-09-15 13:05:19.060180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9eeba5e3bd'
down_revision: Union[str, Sequence[str], None] = '8056fb9dcdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_gasto', sa.Column('activo', sa.Integer(), nullable=True))
    op.add_column('tipo_pago', sa.Column('activo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_pago', 'activo')
    op.drop_column('tipo_gasto', 'activo')
    # ### end Alembic commands ###
