"""add id_pedido to compra and precio_compra to detalle_pedido

Revision ID: 8056fb9dcdd4
Revises: c6b10c109ca6
Create Date: 2026-09-15 11:17:39.076696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8056fb9dcdd4'
down_revision: Union[str, Sequence[str], None] = 'c6b10c109ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compra', sa.Column('id_pedido', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compra', 'pedido', ['id_pedido'], ['id'])
    op.add_column('detalle_pedido', sa.Column('precio_compra', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_pedido', 'precio_compra')
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.drop_column('compra', 'id_pedido')
    # ### end Alembic commands ###
