"""crear tablas configuracion_general meta_financiera

Revision ID: 84b260ca221f
Revises: ede38a7acf13
Create Date: 2026-08-22 01:29:20.813349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b260ca221f'
down_revision: Union[str, Sequence[str], None] = 'ede38a7acf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_general',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_negocio', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('iva_porcentaje', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('monto_caja_chica_default', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('dias_alerta_stock', sa.Integer(), nullable=True),
    sa.Column('formato_impresion', sa.String(length=20), nullable=True),
    sa.Column('logo_ruta', sa.String(length=255), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_financiera',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('meta_ingresos', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('meta_utilidad', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('meta_gastos', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_financiera')
    op.drop_table('configuracion_general')
    # ### end Alembic commands ###
