"""agregar nit real a la tabla correspondiente

Revision ID: abaca6f1b9b5
Revises: 6d386233ff9b
Create Date: 2026-09-06 21:11:57.086008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaca6f1b9b5'
down_revision: Union[str, Sequence[str], None] = '6d386233ff9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('nit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta', 'nit')
    # ### end Alembic commands ###
