"""crear tablas tipo_pago tipo_gasto gasto caja_turno caja_denominacion caja_chica_movimiento

Revision ID: b44e0d0611e8
Revises: 410c03b57e79
Create Date: 2026-08-22 00:47:01.080858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b44e0d0611e8'
down_revision: Union[str, Sequence[str], None] = '410c03b57e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_gasto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_fijo', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('para_ventas', mysql.TINYINT(), nullable=True),
    sa.Column('para_compras', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_chica_movimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('saldo', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_turno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fondo_inicial', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('total_contado', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_ventas', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('diferencia', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tipo_gasto', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('id_usuario_registra', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_gasto'], ['tipo_gasto.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_registra'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_denominacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_caja_turno', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_caja_turno'], ['caja_turno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'compra_pago', 'tipo_pago', ['id_tipo_pago'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compra_pago', type_='foreignkey')
    op.drop_table('caja_denominacion')
    op.drop_table('gasto')
    op.drop_table('caja_turno')
    op.drop_table('caja_chica_movimiento')
    op.drop_table('tipo_pago')
    op.drop_table('tipo_gasto')
    # ### end Alembic commands ###
