"""agregar unique a rol.nombre

Revision ID: c6b10c109ca6
Revises: 0f11a4e53d50
Create Date: 2026-09-10 09:59:31.415032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b10c109ca6'
down_revision: Union[str, Sequence[str], None] = '0f11a4e53d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rol_nombre', 'rol', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rol_nombre', 'rol', type_='unique')
    # ### end Alembic commands ###
