"""crear tablas para usuarios

Revision ID: e6612785dff3
Revises: 0dcc43df5c7e
Create Date: 2026-08-20 22:29:03.696958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6612785dff3'
down_revision: Union[str, Sequence[str], None] = '0dcc43df5c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('dpi', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('salario_base', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('id_puesto', sa.Integer(), nullable=True),
    sa.Column('id_turno', sa.Integer(), nullable=True),
    sa.Column('activo', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['id_puesto'], ['puesto.id'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dpi')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_modulo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_pago_empleado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('concepto', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permiso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_permiso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('activo', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('log_actividad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('accion', sa.String(length=20), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_actividad')
    op.drop_table('usuario')
    op.drop_table('rol_permiso')
    op.drop_table('historico_pago_empleado')
    op.drop_table('permiso')
    op.drop_table('empleado')
    op.drop_table('turno')
    op.drop_table('rol')
    op.drop_table('puesto')
    op.drop_table('modulo')
    # ### end Alembic commands ###
