"""inventario mas sus relaciones

Revision ID: e78eb216130e
Revises: ef449f4c4e81
Create Date: 2026-08-21 23:38:00.182744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e78eb216130e'
down_revision: Union[str, Sequence[str], None] = 'ef449f4c4e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_movimiento_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('signo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('id_usuario_destino', sa.Integer(), nullable=True),
    sa.Column('leida', mysql.TINYINT(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_fisico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('stock_sistema', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('stock_real', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('diferencia', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('ajustado', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sububicacion'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_ubicacion_origen', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion_origen', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion_destino', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion_destino', sa.Integer(), nullable=True),
    sa.Column('id_referencia', sa.Integer(), nullable=True),
    sa.Column('tabla_referencia', sa.String(length=20), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_sububicacion_destino'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_sububicacion_origen'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_movimiento'], ['tipo_movimiento_inventario.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion_destino'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion_origen'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traslado_sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id_ubicacion_origen', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion_destino', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion_origen', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion_destino', sa.Integer(), nullable=True),
    sa.Column('costo_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('metodo_traslado', sa.String(length=50), nullable=True),
    sa.Column('id_usuario_autoriza', sa.Integer(), nullable=True),
    sa.Column('id_usuario_recibe', sa.Integer(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_sububicacion_destino'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_sububicacion_origen'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion_destino'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion_origen'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_autoriza'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_recibe'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_inventario_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_movimiento_cabecera', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_movimiento_cabecera'], ['movimiento_inventario.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_inventario_detalle')
    op.drop_table('traslado_sucursal')
    op.drop_table('movimiento_inventario')
    op.drop_table('inventario_fisico')
    op.drop_table('alerta')
    op.drop_table('tipo_movimiento_inventario')
    # ### end Alembic commands ###
