"""crear tablas cotizacion detalle_cotizacion

Revision ID: ede38a7acf13
Revises: f62f392ff29b
Create Date: 2026-08-22 01:17:41.545841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede38a7acf13'
down_revision: Union[str, Sequence[str], None] = 'f62f392ff29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('numero_expediente', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_cotizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizacion.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'venta', 'cotizacion', ['id_cotizacion'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venta', type_='foreignkey')
    op.drop_table('detalle_cotizacion')
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
