"""crear tablas producto categoria marca unidad_medida historico_precio

Revision ID: ef449f4c4e81
Revises: e6612785dff3
Create Date: 2026-08-21 23:12:24.201978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef449f4c4e81'
down_revision: Union[str, Sequence[str], None] = 'e6612785dff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidad_medida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('abreviatura', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_marca', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_sububicacion', sa.Integer(), nullable=True),
    sa.Column('id_unidad_compra', sa.Integer(), nullable=True),
    sa.Column('id_unidad_venta', sa.Integer(), nullable=True),
    sa.Column('factor_conversion', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('precio_compra', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_venta', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_automatico', mysql.TINYINT(), nullable=True),
    sa.Column('margen_ganancia', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('stock_actual', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('stock_minimo', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('stock_maximo', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('activo', mysql.TINYINT(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['id_sububicacion'], ['sububicacion.id'], ),
    sa.ForeignKeyConstraint(['id_unidad_compra'], ['unidad_medida.id'], ),
    sa.ForeignKeyConstraint(['id_unidad_venta'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('historico_precio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('precio_anterior', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('precio_nuevo', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_precio')
    op.drop_table('producto')
    op.drop_table('unidad_medida')
    op.drop_table('marca')
    op.drop_table('categoria')
    # ### end Alembic commands ###
