"""crear tablas venta detalle_venta metodo_pago_venta servicio_adicional detalle_servicio

Revision ID: f62f392ff29b
Revises: b44e0d0611e8
Create Date: 2026-08-22 01:02:50.508236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62f392ff29b'
down_revision: Union[str, Sequence[str], None] = 'b44e0d0611e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('id_cotizacion', sa.Integer(), nullable=True),
    sa.Column('id_caja_turno', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('descuento', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('descuento_porcentaje', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_caja_turno'], ['caja_turno.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('costo_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo_pago_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_tipo_pago', sa.Integer(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_pago'], ['tipo_pago.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicio_adicional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto_material', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('monto_mano_obra', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_servicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_servicio_adicional', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('costo_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio_adicional'], ['servicio_adicional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_servicio')
    op.drop_table('servicio_adicional')
    op.drop_table('metodo_pago_venta')
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    # ### end Alembic commands ###
